### ISSUE TITLE
Suggestions for release readiness

### ISSUE THREAD

**Issue by ablaom** [JuliaAI/TreeRecipe.jl#1]
- [x] Add CI (GH action, say) including codecov
- [x] Install TagBot
- [x] Add CompatHelper (you need to create a deploy key and secret key for this)
- [x] Add build /  code coverage badges for the README

Probably easier (although not essential) if you do this after transferring to JuliaAI, if that is still your plan. You are author of both and should be able to do this easily (go to bottom of Settings tab). 

Here's a recent example: https://github.com/JuliaAI/CategoricalDistributions.jl/tree/dev/.github/workflows

**Comment by roland-KA** [comment]
HI @ablaom,  I've added now all of the above (and moved the repo to JuliaAI). Could you have a look on it, if it is really complete?

I didn't understand what a deploy key and secret key are (for the CompatHelper). How do I get them and where do I have to put them?

**Comment by ablaom** [comment]
This looks good. 

> I didn't understand what a deploy key and secret key are (for the CompatHelper). How do I get them and where do I have to put them?

See #3 

One last suggestion is that we change the default branch from `main` to `master` for consistency with the other JuliaAI repos. You can rename a branch on github but probably safest is to locally create and push to GH a new branch called `master`, based on `main`, and change the default branch to `master` [here](https://github.com/JuliaAI/TreeRecipe.jl/settings/branches). You can delete `main` after you're happy you don't need it locally anymore. Again good to do this before registering.

**Comment by roland-KA** [comment]
**Registration**
Now everything is ready and I've tried to start the registration process. But unfortunately I don't have sufficient rights on the `TreeRecipe.jl` repo to register it. The JuliaTeam Registrator says "_You do not have permission to modify this app on JuliaAI. Please contact an Organization Owner._" when I try to give it repository access for registering. I'm stuck here:

<img width="537" alt="image" src="https://user-images.githubusercontent.com/80126696/205327857-a415937a-330f-478c-b6e9-1293eed7bbbf.png">

Could you change that?

**Branch protection rules**
Apart from that GitHub warns that there are no branch protection rules on the repo. Which rules do you typically use for JuliaAI repos?

**Comment by ablaom** [comment]
That's frustrating. You're already a member of Julia AI and already have Admin rights for TreeRecipe.jl:

![Screen Shot 2022-12-03 at 7 01 36 PM](https://user-images.githubusercontent.com/30517088/205427451-0fe6a9f6-d2aa-4363-aba6-fa44bbeecfdc.png)

I'm not sure what else I can do but have gone ahead and triggered registration. I expect you will be able to register new versions - I'll set up a pinned issue for the purpose shortly. 

https://github.com/JuliaRegistries/General/pull/73371

**Comment by roland-KA** [comment]
Ok, thanks! GitHub seems to me sometimes overly complex.

And do you have any recommendations to my question on branch protection rules?
> **Branch protection rules**
Apart from that GitHub warns that there are no branch protection rules on the repo. Which rules do you typically use for JuliaAI repos?

**Comment by ablaom** [comment]
To be honest, I haven't bothered for a small repo like this but it's probably a good idea.  This is what I have at MLJBase.jl:


<img width="1032" alt="Screen Shot 2022-12-05 at 9 45 14 AM" src="https://user-images.githubusercontent.com/30517088/205515402-17c3808b-dc92-4d18-814a-c737ee98efba.png">

And I have "Do not allow bypassing the above settings" ticked.

**Comment by roland-KA** [comment]
Ok thanks! I've added this configuration to `TreeRecipe.jl` so that it is consistent to the other repos in JuliaAI.
